Pizzeria/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizzas/urls.py
from django.urls import path
from . import views

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizs', views.pizs, name='pizs'),
    path('pizs/<int:pizza_name_id>/',views.pizza,name='pizza'),
    path('comments/<int:pizza_name_id>/',views.comments,name='comments'),

]

pizzas/models.py
from django.db import models
# Create your models here.

#u - admin p - John0118

class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)

    def __str__(self):
        return self.pizza_name

class Topping(models.Model):
    pizza_name = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    toppings = models.TextField()

    def __str__(self):
        return self.toppings

class Image(models.Model):
    pizza_name = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')



class Comments(models.Model):
    pizza_name = models.ForeignKey(Pizza, related_name='details', on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True,blank=True)

    def __str__(self):
        return self.text

pizzas/forms.py
from django import forms
from .models import *


class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['text']
        labels = {'text':''}

        widgets = {'text': forms.Textarea(attrs={'cols':80})}

pizzas/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from datetime import datetime, date

# Create your views here.
def index(request):
    return render(request, 'pizzas/index.html')

def pizs(request):
    pizs = Pizza.objects.order_by()

    context = {'all_pizzas':pizs}
    # the key is the variable name you are going to use in the HTML file
    # the value is the variable name you are using in views.py
    return render(request, 'pizzas/pizs.html', context)

def pizza(request, pizza_name_id):
    pizza_name = Pizza.objects.get(id=pizza_name_id)
    toppings = Topping.objects.filter(pizza_name=pizza_name)
    acomment = Comments.objects.filter(pizza_name=pizza_name_id)
    image= Image.objects.filter(pizza_name=pizza_name_id)

    context = {'pizza_name':pizza_name, 'toppings':toppings, 'acomment':acomment,'image':image}

    return render(request, 'pizzas/pizza.html', context)



def comments(request, pizza_name_id):
    pizza_name = Pizza.objects.get(id=pizza_name_id)

    if request.method != 'POST':
        form = CommentsForm()
    else:
        form = CommentsForm(data=request.POST)
        if form.is_valid():
            comments=form.save(commit=False)
            comments.pizza_name = pizza_name
            comments.save()
            return redirect('pizzas:pizza', pizza_name_id=pizza_name_id )

    context = {'form':form, 'pizza_name':pizza_name}

    return render(request,'pizzas/comments.html', context)

pizzas/templates/pizzas/base.html
<p>
    <a style="font-size:25px" href="{% url 'pizzas:index' %}"> Homepage </a>
    <br>
    <a style="font-size:25px" href="{% url 'pizzas:pizs' %}"> Pizzas </a>
</p>

{% block content %}

{% endblock content %}

pizzas/templates/pizzas/comments.html
{% extends "pizzas/base.html" %}
{% load static %}

{% block content %} 
<link rel="stylesheet" href="{% static 'colors2.css' %}"> 

<p><a href="{% url 'pizzas:pizza' pizza_name.id %}"> {{ p }} </a></p>

<h2><p>Pizza Name: {{ pizza_name.pizza_name }} </p></h2>

<form action="{% url 'pizzas:comments' pizza_name.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}

    <button name="submit">Submit Comment</button>
</form>

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'colors.css' %}"> 

<p style="font-size:70px"> Welcome to John's Pizzaria! </p>
<img src="{% static 'shop.jpg' %}" class="img-thumbnail" style="max-height: 279px" alt=""><img src="{% static 'pepperoni.jpg' %}" class="img-thumbnail" style="max-height: 300px" alt="">>
<p style="font-size:35px">Home of the greatest pizzas in the world!!!
</p>


{% endblock content %}

pizzas/templates/pizzas/pizs.html
{% extends "pizzas/base.html" %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'colors2.css' %}"> 
<p style="font-size:50px"></pstyle> Pizzas: </p>
<ul> 
    {% for p in all_pizzas %}
    <li> 
        <a style="font-size:25px" href="{% url 'pizzas:pizza' p.id %}"> {{ p }} </a>
    </li>

    {% empty %}
    <li> no pizzas have been added yet </li>
    {% endfor %}
    
</ul>
<img src="{% static 'inside.jpg' %}" class="img-thumbnail" style="max-height: 279px" alt=""><img src="{% static 'meatlovers.jpg' %}" class="img-thumbnail" style="max-height: 279px" alt=""><img src="{% static 'shop.jpg' %}" class="img-thumbnail" style="max-height: 279px" alt=""><img src="{% static 'cheese.jpg' %}" class="img-thumbnail" style="max-height: 279px" alt="">

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'colors2.css' %}"> 

<p style="font-size:35px"> Pizza: {{ pizza_name }} </p> 

{% for i in image %}
<div class="'col-md-4">
    <img src="{{ i.image.url }}" class="img-responsive" style="width: 15%; margin-right:10px;" />
</div>
{% empty %}
<p> No image yet </p>
{% endfor %}

<form method ='POST'>
    <p style="font-size:30px"> List of Toppings in this pizza: </p>   
    <ul> 
        {% for t in toppings %}
        <li> {{ t.toppings }} </li>

        {% empty %}
        <li> no toppings listed for this pizza </li>
        {% endfor %}
        
    </ul>
    <p style="font-size:30px"> Comments: </p>
    <ul>
        {% for c in acomment %}
        <li>{{ c.text }}</li>

        {% empty %} 
        <p> No comments </p>
        {% endfor %}
        
    </ul>
    <p><a href="{% url 'pizzas:comments' pizza_name.id %}">LEAVE A COMMENT HERE!</a></p>
</form>




{% endblock content %}